
import {
    ClothesHoodie,
    HamburgerOne,
    Commodity,
    Sofa,
    Phone,
    Outdoor,
    Makeups,
    ChildWithPacifier,
    Cat,
    Car,
    Train,
    Homestay,
    Hotel,
    Fan,
    School,
    Health,
    XiaoduHome,
    PhoneBooth,
    IncomeOne,
    Other,
    HeavyMetal,
    Sleaves,
    Strongbox,
    PaperMoneyTwo,
    TreasureChest,
    Credit,
    WaterRate,
    RedEnvelope,
    Peoples,
    Finance,
    Income,
} from '@icon-park/react'

export const billNameMap = {
    CateringFood: { icon: (size) => <HamburgerOne theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "餐饮美食" },
    ClothingDress: { icon: (size) => <ClothesHoodie theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "服饰装扮" },
    DailyGeneralMerchandise: { icon: (size) => <Commodity theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "日用百货" },
    HomeDecoration: { icon: (size) => <Sofa theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "家居家装" },
    DigitalAppliances: { icon: (size) => <Phone theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "数码电器" },
    SportsOutdoor: { icon: (size) => <Outdoor theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "运动户外" },
    BeautyHair: { icon: (size) => <Makeups theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "美容美发" },
    MotherAndBaby: { icon: (size) => <ChildWithPacifier theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "母婴亲子" },
    Pets: { icon: (size) => <Cat theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "宠物" },
    TransportationTravel: { icon: (size) => <Train theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "交通出行" },
    CarMaintenance: { icon: (size) => <Car theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "爱车养车" },
    HousingProperty: { icon: (size) => <Homestay theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "住房物业" },
    HotelTourism: { icon: (size) => <Hotel theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "酒店旅游" },
    CulturalLeisure: { icon: (size) => <Fan theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "文化休闲" },
    EducationTraining: { icon: (size) => <School theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "教育培训" },
    MedicalHealth: { icon: (size) => <Health theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "医疗健康" },
    LifeService: { icon: (size) => <XiaoduHome theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "生活服务" },
    PublicService: { icon: (size) => <PhoneBooth theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "公共服务" },
    BusinessService: { icon: (size) => <HeavyMetal theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "商业服务" },
    PublicWelfareDonation: { icon: (size) => <Sleaves theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "公益捐赠" },
    MutualAssurance: { icon: (size) => <Strongbox theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "互助保障" },
    InvestmentFinance: { icon: (size) => <PaperMoneyTwo theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "投资理财" },
    Insurance: { icon: (size) => <TreasureChest theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "保险" },
    CreditBorrowAndRepay: { icon: (size) => <Credit theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "信用借还" },
    RechargePayment: { icon: (size) => <WaterRate theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "充值缴费" },
    Income: { icon: (size) => <Income theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "收入" },
    TransferRedPacket: { icon: (size) => <RedEnvelope theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "转账红包" },
    RelativesAndFriendsPay: { icon: (size) => <Peoples theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "亲友代付" },
    AccountDepositAndWithdrawal: { icon: (size) => <Finance theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "账户存取" },
    Refund: { icon: (size) => <IncomeOne theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "退款" },
    Others: { icon: (size) => <Other theme="two-tone" size={size || 16} fill={['#333', '#2F88FF']} />, name: "其他" }
}